### ISSUE TITLE
LDAP Authentication for users to submit tickets.

### ISSUE THREAD

**Issue by suckamucka** [osTicket/osTicket-plugins#1]
I have cloned both osTicket-1.8 develop-next branch and the core-plugins.
LDAP configuration was way too easy to configure for Active Directory.
I see it works for staff, but how do I get it to work for users trying to submit a ticket?
Thanks

**Comment by greezybacon** [comment]
Is that a complaint concerning the setup?

For client auth: osTicket doesn't have the concept of client logins yet. When we add it, we will extend auth to clients

**Comment by suckamucka** [comment]
Ha. Not a complaint at all. Great work.

That makes sense. I didnt read anywhere that indicates it was not available
to clients, so I was unsure how to configure it.

**Comment by Trippzc** [comment]
I would also love for the user authentication functionality via LADP. It would definitely put our users at ease. Simple makes them very happy. Awesome job by the way!

**Comment by greezybacon** [comment]
We're just about there. This is implemented in #18 and osTicket/osTicket-1.8#725

**Comment by greezybacon** [comment]
This is officially implemented in osTicket 1.9.0 and auth-ldap v0.5
