### ISSUE TITLE
Auth-ldap + auth-passthru work for clients, but not staff.

### ISSUE THREAD

**Issue by mfoustv** [osTicket/osTicket-plugins#117]
We just rolled out a new install of osTicket with the auth-passthru and auth-ldap plugins. Both plugins work great on the client login, but auth-passthru is not working on the staff login.

When a client logs in, we verified that Kerberos is working and passes through the user's AD credentials. We can use klist to show that a Kerberos ticket is generated and there are no errors on login.

When staff logs in, we can see a Kerberos ticket generated in klist but the credentials are not passed through to the login. The staff still has to log in by manually typing their AD credentials into the web form at /scp/login.php.

I don't think it's an IIS configuration problem because client logins work fine through Kerberos.

No PHP errors are generated. nor are any errors generated in the osTicket system log. (We have the logging level set to DEBUG.)

This problem appears to be similar to #33 from 2014 (https://github.com/osTicket/osTicket-plugins/issues/33) but that user's fix didn't work for us.

Server: IIS 8.5 on Windows Server 2012 R2
PHP: 5.3.28
DB: MariaDB 10.1
osTicket version: 1.9.15 (70898b3)
auth-ldap version: 0.6.2
auth-passthru version: 0.2
LDAP: Microsoft Active Directory

Thanks in advance.

**Comment by ntozier** [comment]
I'm running a similar setup. (IIS 8.5, PHP 5.6.12) and I've never had any luck with HTTP-Auth working. I always assumed that it was IIS since I've spoken with some Apache2 users and they haven't had the same problems as me.  So I personally won't be able to help you, but I am willing to test any fixes the devs might offer us. :)

**Comment by mfoustv** [comment]
Well, glad to know it's not just me.
As a partial workaround, I added the following code into /include/staff/login.tpl.php:

```
$custom_iisuser = strtolower(htmlspecialchars(str_replace("NTDOMAIN\\", "", ($_SERVER['REMOTE_USER']))));
echo "<script type='text/javascript'>";
echo "document.getElementById('name').value='".$custom_iisuser."'";
echo "</script>";
```

It doesn't automatically log staff in, but it does fill in the username field to cut out a little bit of typing.

**Comment by laylantrin** [comment]
I had the same issue: worked for clients, not for staff. I was able to resolve it by doing a couple of things:
  1.  Under Manage Agent screen for each staff agent, there should be a section called "Authentication Backend" if you have the plugin installed correctly (which if it is working for the clients, you do). You want that to be the default option, "--Use any available backend --". _(If you have a lot of agents/staff, and you are comfortable with the database side, you can update table staff and set backend to NULL)_
  2. There MUST be _something_ set for the staff user's password. It doesn't matter what it is, it can be anything, and they don't even need to know what it is. It just wants something in that field. Again, you can do this one by one using the Set Password button under the Manage Agent screen, or you can update all of your staff/agents at once in the database, same table, field name is passwd.

This works for every one of my staff users. If they are logged into their domain account on their PC, then it passes their authentication through to the portal. Tested and working in IE, Chrome, and Firefox (Firefox requires a config change to trusted uris to work with passthrough, but that is true for all passthrough, not just OSTicket)

For reference, my configs:
Server: IIS 8.5 on Windows Server 2012 R2
PHP: 5.6
DB: MySQL
osTicket version: 1.10
auth-ldap version: 0.6.2
auth-passthru version: 0.2
LDAP: Microsoft Active Directory

**Comment by lupin3rd** [comment]
I can confirm that if i set "--Use any available backend --" to agents, they can login successfully.
My config:
I'm using Apache and osTicket 1.9.14 and LDAP Microsoft AD

**Comment by mfoustv** [comment]
Verified. This works. Thank you!
