### ISSUE TITLE
How to add any email address as user of osTicket

### ISSUE THREAD

**Issue by macmkelp1983** [osTicket/osTicket-plugins#118]
Hello Github members, 

Sorry, i have a question.

How can i add a user with a diferent email address format for example: xxxxx@123.fri, it's because we have a internal email server and those email address are such rare.

Thanks.

**Comment by ntozier** [comment]
Go to Agent Panel -> Users
Click Add User.

**Comment by macmkelp1983** [comment]
Does not admit not comun domain format, did admit, .com, .net, but not .fcia for example.

**Comment by ntozier** [comment]
Admin panel -> Emails -> Settings
uncheck "Verify Email Addresses:"

**Comment by macmkelp1983** [comment]
So many Thanks ntozier!

**Comment by ntozier** [comment]
Very welcome. :)
