### ISSUE TITLE
Users get Access Denied, Agents authenticate successfully, with Active Directory

### ISSUE THREAD

**Issue by kcorum** [osTicket/osTicket-plugins#128]
osTicket version - 1.10
PHP - 5.6.30
Windows Server 2012 R2

I've installed osTicket and I am trying to allow the users to authenticate to our Active Directory. This works with the Agent - I can create an agent, set it to Active Directory authenticate and they login with no problems. However, when I create a User and set it login with Active Directory, I get Access Denied. Don't both Agents and Users - use the same LDAP settings in the LDAP AUthenticate and Lookup Plugin? I

Thanks for any help/pointers.
Kristi

**Comment by ntozier** [comment]
Have you implemented the two fixes in this thread?
https://github.com/osTicket/osTicket/pull/3456

**Comment by kcorum** [comment]
I see one fix in #3456 - removed line in ajax.users.php. What is the other fix in that thread?

**Comment by ntozier** [comment]
Comment 8 #3441
https://github.com/osTicket/osTicket/pull/3441

**Comment by kcorum** [comment]
I have change the file and this is how those sections of my file appears. It still doesn't work.

function addRemoteUser($bk, $id) {
        global $thisstaff;
	   $id = str_replace('/','\\',$id);
        if (!$thisstaff)
            Http::response(403, 'Login Required');


$users->union(User::objects()
                    ->values_flat('id', 'name', 'default_email__address')
                    ->filter(array(
                        'emails__address__in' => $emails
                )));

**Comment by jianfzhu** [comment]
i also have same issue. how about now?

**Comment by jianfzhu** [comment]
@kcorum  are you fix the issue?

**Comment by kcorum** [comment]
I never got it to work so I changed to Spiceworks a few months ago.

**Comment by mahjoubakhabbiza** [comment]
hi, 
I have an issue to register users in osticket version1.14 and also osticket v1.12 with ldap. I get access denied.
Ldap plugin is set correctly. any help please?

**Comment by JediKev** [comment]
@mahjoubakhabbiza 

You'd want to check all error logs for any related errors. (Apache/IIS Error Logs, PHP Error Logs, MySQL Error Logs, Browser Console Logs, osTicket System Logs) `Access Denied` sounds like the webserver is denying access to the requested resource.

**EDIT:**
You may benefit from our [Forum here](https://forum.osticket.com). You can search the Forum to see if someone has already ran into this issue and have addressed it. If not, you can create a post and the community will assist you.

Cheers.

**Comment by towerplease** [comment]
I got it working because i missconfigured something, just in case you did this too, here is my solution:

To have user-LDAP/AD login to work, you registermethod needs to be "public", otherwise you get access denied because its not allowed to create a new user. When you login with AD-Credentials there is automatically created a osTicket-User.

Hope this helps some of you.

I would recommend to osTicket-devs to still make it possible to login, even when the registermethod is set to private.

**Comment by JediKev** [comment]
@towerplease 

If you are talking about the osTicket Registration method, if it's set to Private that means only Agents can create User accounts. This is why a User cannot create their own account. If you would like Users to create their own account the Registration Method has to be Public.

Cheers.
