### ISSUE TITLE
auth-ldap Issue searching for users

### ISSUE THREAD

**Issue by Dubz** [osTicket/osTicket-plugins#132]
So I'm having an issue when searching for users, whether to add a new user or open a ticket.

The search on the admin panel to add new agents works just fine, and I can add any potential user as an agent like I did the agents already. For some reason though, I can't get it to work on any part of the agent panel for users.

I opened /var/log/php-fpm/www-error.log and found this:
```
[16-Feb-2018 13:48:25 UTC] PHP Fatal error:  Uncaught exception 'OrmException' with message 'Union queries must have matching values counts' in /home/it/public_html/support.example.com/include/class.orm.php:1283
Stack trace:
#0 /home/it/public_html/support.example.com/include/ajax.users.php(90): QuerySet->union(Object(QuerySet))
#1 [internal function]: UsersAjaxAPI->search()
#2 /home/it/public_html/support.example.com/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#3 /home/it/public_html/support.example.com/include/class.dispatcher.php(38): UrlMatcher->dispatch(false, Array)
#4 /home/it/public_html/support.example.com/include/class.dispatcher.php(120): Dispatcher->resolve(false, Array)
#5 /home/it/public_html/support.example.com/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL)
#6 /home/it/public_html/support.example.com/scp/ajax.php(262): Dispatcher->resolve('/users')
#7 {main}
  thrown in /home/it/public_html/support.example.com/include/class.orm.php on line 1283
```

Here's what I'm running for this too:

osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Apache/2.4.6 (CentOS) PHP/5.6.33
MySQL Version | 5.5.56
PHP Version | 5.6.33

Plugin Version: 0.6.3 (latest)

This is a fresh install, no tickets/users added. I changed some settings, added the plugin, and added new agents to work through the LDAP plugin with no issues with this software until now (from what I can tell).

**Comment by ntozier** [comment]
Have you applied the two fixes in this PR?
https://github.com/osTicket/osTicket/pull/3456

(the PR has the info for one of them, and there is a second link to fix something else in the comments)

**Comment by Dubz** [comment]
This works, thanks!

Is there a way to have names updated in case it ever changes on the LDAP server? Like a refresh of some sort? If I can do all current users that'd be great, but if I have to do it one at a time then I can manage that too.

**Comment by ntozier** [comment]
We use the adSync plugin from software-mods.com to re-sync our AD users on a schedule. It was written for AD but may work for other LDAP implementations (no idea really).

**Comment by Dubz** [comment]
There was no pricing information for this found on their site. I went to the buy now to see what it would say, and I found it, but we aren't in that high of need to do this. I was mostly curious to do this, but it's something I could probably manage on my own (and later make a cron if needed).

Anyways, glad I have this all in working order now. Thanks!!

**Comment by ntozier** [comment]
very welcome.
