### ISSUE TITLE
Unable to Login after LDAP is configured

### ISSUE THREAD

**Issue by workbykiran** [osTicket/osTicket-plugins#133]
Hi,

I did a fresh installation of osticket 1.10.1 and then copied the ldap plugin and then configured it. however after configuration, only the admin user (created during configuration of osticket for the first time) is working. I was doing an integration with yunohost where it has ldap server in the same server where osticket is also installed. I also tried creating the same Agent with same details (firstname, lastname, username, email, password) in both osticket and also in yunohost. However when trying to login into osticket with any test users, it doesnt work. only admin user can login into osticket.

php version: 5.6
osticket: 1.10.1
OS: Linux Debian Jessie

Ldap configuration:
LDAP Server: 192.168.0.100:389
Search User: cn=admin,dc=yunohost,dc=org
Password: Administrator password given
Search Base: (&(objectClass=mailAccount)(uid={}))
LDAP Schema: postfix account (rfc 2307)

I even tried keeping LDAP schema as Automatic Detect and empty value for Search Base.

**Comment by ntozier** [comment]
Have you applied this patch?
https://github.com/osTicket/osTicket/pull/3456
or the one in the comments?

**Comment by workbykiran** [comment]
I applied the above patch by deleting line no: 87 however still iam not able to log in. Can you let me know where we can have logs so that we can understand the error.
Also on the other hand, if you have some idea on yunohost, i would also request to check if the ldap config is correct or not.
But when configured in osticket, it doesnt gives any error.

**Comment by ntozier** [comment]
You would have to look at your: 
PHP error logs for PHP errors.
LDAP connection logs for connection failures (and reason).

I cannot tell you if your LDAP config in the plugin is correct since I use Active Directory.  I can tell you that my search base looks nothing like yours.

OU=All_Users,DC=corp,DC=domain,DC=local

**Comment by workbykiran** [comment]
I could see the heading as: Generic configuration for LDAP
Not necessary if Active Directory is configured above
 but if i leave the Active directory section like default domain as empty and tries to configure only the LDAP section, it gives an error at Default domain in Active Directory section saying Fully-qualified domain name is expected.
Is it mandatory to configure that?

**Comment by workbykiran** [comment]
Finally i configured the ldap and i got the message as ldap configured successfully. However if i want to authenticate a user present in ldap with osticket, then unless that user is not created inside osticket as Agent, and configure the authentication as Ldap then only i was able to login. Is there any way to avoid creation of users inside osticket but use the users directly from LDAP server itself?
Could be a weird question, but i would like to avoid here so that central configuration is applicable from LDAP server itself.

**Comment by workbykiran** [comment]
Just to update info, i have nginx webserver only and no apache. is there any way either to use http pass through or any other means where i login into an application (integrated with ldap and sso) and from it, i will open osticket which should auto login into osticket without asking for login.

**Comment by ntozier** [comment]
You have to create the users/agent in osTicket [and give them permission to login via LDAP or any authentication provider] for them to be able to log in.

osTicket doesn't support nginx so I cannot really comment on that since I dont use it.  I imagine that you would have to run the authentication http pass through plugin and hope that it works with a non Apache web server. [Note: I couldn't seem to get it running with IIS.]

**Comment by workbykiran** [comment]
Ok. I tried with Nginx and standard osticket works well. however i did some changes to meet LDAP through SSO for my environment and looks ok at the moment, but has some issues with logout. neverthless i will figure it out. Thanks.
