### ISSUE TITLE
Migrated to a new server... Error 500 only with S3

### ISSUE THREAD

**Issue by mrabino1** [osTicket/osTicket-plugins#136]
Migrated to a new server (whm) using CentOS from an Ubuntu box. DB and filesystem replicated exactly (less username and password deltas). When trying to reconnect the s3 plugin, I am constantly getting an error 500.

**Comment by mrabino1** [comment]
I have the legacy .phar file... (as it was copied over.. none of the s3 creds changed. )

**Comment by mrabino1** [comment]
Solved. hydrating is really important!

**Comment by jahir3819** [comment]
Hi @mrabino1 I am exactly experiencing this issue. Can you please let me know what you did for solving this issue.

Thank you in advance.
