### ISSUE TITLE
How to Add column in Ticket List

### ISSUE THREAD

**Issue by brunotda** [osTicket/osTicket-plugins#145]
I need add organization in a table ticket list, i looked for the data source from table in "tickets.inc.php'"but didn't find it.

**Comment by JediKev** [comment]
@brunotda

It’s called Custom Columns and Custom Queues released in `1.11.0rc-1` available here:
http://osticket.com/download

Cheers.

**Comment by brunotda** [comment]
Work... TKS. =D
