### ISSUE TITLE
HTTP Error 500 OsTicket

### ISSUE THREAD

**Issue by nanasecr** [osTicket/osTicket-plugins#150]
Hi, I am currently doing an installation of osticket but when I send the link, I get the following problem.
Can someone help me or give me a guide on how to solve it?

HTTP Error 500.19 - Internal Server Error The requested page cannot be accessed because the related configuration data for the page is invalid. Detailed Error Information: Module IIS Web Core Notification Unknown Handler Not yet determined Error Code 0x8007000d Config Error Config File \\?\Osticket\web.config Requested URL http://localhost:80/ Physical Path Logon Method Not yet determined Logon User Not yet determined

Regards.
![image](https://user-images.githubusercontent.com/45568013/49386470-39a72880-f6e5-11e8-8104-518d3758d9fe.png)

**Comment by ntozier** [comment]
This thread does not appear to be about a plugin... I would recommend that you seek support at the support forums. https://forum.osticket.com/

Also make sure that you read the posting guidelines located in this thread: [Please read before requesting assistance](https://forum.osticket.com/d/89131-please-read-before-requesting-assistance).  The more information you give us the better we will be able to assist you. Thank you.

Please close this issue report.
