### ISSUE TITLE
Unable to create pahr.

### ISSUE THREAD

**Issue by bmmcwhirt** [osTicket/osTicket-plugins#155]
Kernel (Debian 9)
`root@phobia2:/var/www/html/osTicket/include/plugins/osTicket-plugins# uname -a
Linux phobia2 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
`

osTicket Information
`
Server Information
--
osTicket Version | v1.10.5 (13f2f4a) —  Up to date
Web Server Software | Apache/2.4.25 (Debian)
MySQL Version | 10.1.37
PHP Version | 7.0.33-0+deb9u3

`

Error:
`root@phobia2:/var/www/html/osTicket/include/plugins/osTicket-plugins# php -dphar.readonly=0 make.php build /var/www/html/osTicket/include/plugins/
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar '/var/www/html/osTicket/include/plugins/.phar', file extension (or combination) not recognised or the directory does not exist in /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php:380
Stack trace:
#0 /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php(380): Phar->__construct('/var/www/html/o...')
#1 /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php(336): PluginBuilder->_build('/var/www/html/o...', Array)
#2 /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php(240): PluginBuilder->run(Array, Array)
#3 /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php(704): Module->_run('make.php')
#4 {main}
  thrown in /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php on line 380
`

**Comment by ntozier** [comment]
Looks to me like you are trying built a phar called ''
Since '' probably isn't a rational folder name...

maybe try:
`php -dphar.readonly=0 make.php build /var/www/html/osTicket/include/plugins/PLUGINFOLDERNAME`

**Comment by bmmcwhirt** [comment]
Nope I still get the error:

`
is@phobia2:/var/www/html/osTicket/include/plugins/osTicket-plugins$ php -dphar.readonly=0 make.php build /var/www/html/osTicket/include/plugins/osTicket-plugins/
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar '/var/www/html/osTicket/include/plugins/osTicket-plugins/.phar', file extension (or combination) not recognised or the directory does not exist in /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php:380
Stack trace:
#0 /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php(380): Phar->__construct('/var/www/html/o...')
#1 /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php(336): PluginBuilder->_build('/var/www/html/o...', Array)
#2 /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php(240): PluginBuilder->run(Array, Array)
#3 /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php(704): Module->_run('make.php')
#4 {main}
  thrown in /var/www/html/osTicket/include/plugins/osTicket-plugins/make.php on line 380
`

This is the directory of the git clone and make.php does exist in the directory.

**Comment by JediKev** [comment]
@bmmcwhirt 

Please read the CLI help if you don't know how to use the command. You can invoke this by passing the `-h` argument. Example:
```
$ php make.php build -h
Inspects, tests, and builds a plugin PHAR file

Usage:
    make.php  [options] action plugin [arguments]

...
```

The proper usage of the command is `$ php make.php  [options] action plugin [arguments]`. Below is an example of how to use the command for the `auth-ldap` plugin:
```
$ php make.php build auth-ldap -v
```

Note:
`-v` is for "Verbose" meaning it will explain what it's doing.

Cheers.

**Comment by bmmcwhirt** [comment]
> @bmmcwhirt
> 
> Please read the CLI help if you don't know how to use the command. You can invoke this by passing the `-h` argument. Example:
> 
> ```
> $ php make.php build -h
> Inspects, tests, and builds a plugin PHAR file
> 
> Usage:
>     make.php  [options] action plugin [arguments]
> 
> ...
> ```
> The proper usage of the command is `$ php make.php [options] action plugin [arguments]`. Below is an example of how to use the command for the `auth-ldap` plugin:
> 
> ```
> $ php make.php build auth-ldap -v
> ```
> Note:
> `-v` is for "Verbose" meaning it will explain what it's doing.
> 
> Cheers.

Thanks, I was trying to follow the readme.md instructions too literally.

I'm closing this and thanks again.
