### ISSUE TITLE
Default Domain too short

### ISSUE THREAD

**Issue by ijeffers** [osTicket/osTicket-plugins#16]
Our AD FQDN is 33 characters long (don't ask, I didn't set the domain up) which doesn't fit in the OSTicket auth-ldap field. 

Could this be increased?

Thanks

**Comment by ntozier** [comment]
This is a dupe issue. See https://github.com/osTicket/core-plugins/pull/15

**Comment by ijeffers** [comment]
That issue seemed specific for the file attachement plugin though, I can't bind using ldap-auth because our FQDN is to large (won't let me input the last 3 characters).

Can't find the file you've modified in the ldap-auth plugin in order to increase the Default Domain field.

Sorry

**Comment by greezybacon** [comment]
maxlength bites again!

**Comment by ijeffers** [comment]
Probably already realise this, but it's an input problem only. Manually making the change in the DB allows the domain to be saved and used correctly.

**Comment by greezybacon** [comment]
Fixed in `develop`. Thanks for the report
