### ISSUE TITLE
Expire variable in url image 

### ISSUE THREAD

**Issue by bertaviader** [osTicket/osTicket-plugins#164]
Hello,

We have a Osticket version 1.9.12 with the plugin attachment on the filesystem. We have a problem, the images are disapearing, but we don't know why. 
The strange think is the url:
https://url.osticket/file.php?key=xxxxx&expires=1551139200&signature=7xxxxx&disposition=inline

Do you know if it's possible that the image are expiring?

Thank you,
Berta

**Comment by JediKev** [comment]
@bertaviader

Yes, if you use a direct link for the attachment it will eventullay expire hence the `expires` parameter on the URL.

Cheers.

**Comment by bertaviader** [comment]
But the image will be still in the server?

**Comment by bertaviader** [comment]
Okay, thank you!
