### ISSUE TITLE
Suggestion: Rename "Google Authenticator" to 2FA Authenticator App

### ISSUE THREAD

**Issue by joeldeteves** [osTicket/osTicket-plugins#198]
Hello,

This is purely cosmetic and very minor (perhaps even bordering on pedantic) but: being that any Authenticator App works with this plugin, would it not make more sense to simply call it "2FA Authenticator App"?

Calling it "Google Authenticator" in the login screen implies that agents must download and install Google's 2FA app to their phone, rather than use any available app (Authy, Duo, Microsoft, etc).

Thank you,

**Comment by joeldeteves** [comment]
I think this has been addressed in 1.16.1. Thanks!

**Comment by JediKev** [comment]
@joeldeteves 

This was addressed as part of the following pull:
- https://github.com/osTicket/osTicket-plugins/pull/204

Cheers.
