### ISSUE TITLE
First Name/ Last Name reversed when Adding New Staff

### ISSUE THREAD

**Issue by stf675** [osTicket/osTicket-plugins#22]
when I am adding new staff by looking up username, the form populates incorrectly:

First Name filed populates with  Lastname, (coma at the end)
Last name field populates with Firstname

Looks like instead of using AD Display Name attribute, instead of corresponding First Name and Last name attributes.

Environment: latest XAMPP
osTicket version 1.8.1.2
AD Auth Plugin ver 0.4
LDAP: AD 2003

**Comment by Chefkeks** [comment]
+1
Same issue here with different environment (Apache, AD 2008R2)

**Comment by greezybacon** [comment]
I think this should be fixed now with the last commits in #18

**Comment by Chefkeks** [comment]
Just tested: Fix works like a charm, even when the person has multiple first name and multiple last names! :)

**Comment by stf675** [comment]
works great
