### ISSUE TITLE
Anyone installed osticket-google-oauth2-plugin successfully recently?

### ISSUE THREAD

**Issue by ait1ispring** [osTicket/osTicket-plugins#221]
I just want to know is there anyone who successfully installed https://github.com/senzil/osticket-google-oauth2-plugin on your Os ticket plugin. I am not sure if this plugin is still working since It keep sending me to a blank page after I log in with Google auth. Please you have any idea, kindly help. Thank you.

Below is the env currently of mine:
OSticket v1.8
Server Software: Apache2 (Ubuntu)
PHP Version: 5.6.40
MySQL Version: 5.7.33

I did:

~~~
<IfModule mod_rewrite.c>

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} (.*/api)

#RewriteRule ^(.*)$ %1/http.php/$1 [L]
RewriteRule ^(.*)$ {put your schema:domain:port}/api/http.php/$1 [L]
</IfModule>
~~~
But it still sends to a blank page. There is no error found on /var/log/apache2/error.log
Is there anything that I can do? Thank you in advance.

**Comment by JediKev** [comment]
@ait1ispring 

GitHub is a place to report issues with the code, create feature requests, or submit a pull request. If you would like to ask questions, please create a post on [our Forum](https://forum.osticket.com).

Cheers.

**Comment by ntozier** [comment]
Also osTicket 1.8 is ancient, no longer supported and well past end of life.
