### ISSUE TITLE
2FA plugin not working with PHP 8.1

### ISSUE THREAD

**Issue by joeldeteves** [osTicket/osTicket-plugins#227]
Hello,

After upgrading from osTicket 1.15.4 -> 1.16.1, I also upgraqded PHP to v 8.1.4

Since then, I also saw I had to replace the Google 2FA plugin with the new 2FA plugin, which I have done.

However, even though the plugin .phar is present in the include dir with the correct permissions applied, it never shows up in the list of plugins.

I also see this error in the logs, which I assume is related:

`NOTICE: PHP message: PHP Fatal error:  Cannot make static method JsonDataParser::parse() non static in class ApiJsonDataParser in /var/www/html/include/class.api.php on line 383`

Is the 2FA plugin compatible with PHP v8.x?

**Comment by JediKev** [comment]
@joeldeteves 

Please read the requirements before upgrading. v1.16.1 requires PHP 8.0 so you must downgrade PHP.

Cheers.

**Comment by joeldeteves** [comment]
> @joeldeteves
> 
> Please read the requirements before upgrading. v1.16.1 requires PHP 8.0 so you must downgrade PHP.
> 
> Cheers.

Thanks, I wasn't aware that was a hard requirement. Do I need to re-run the upgrader after doing so?

**Comment by JediKev** [comment]
@joeldeteves 

Nah, there is only one simply query that runs for the 1.16.x upgrade. You should be fine on that.

Cheers.

**Comment by joeldeteves** [comment]
I downgraded to 8.0.17 but I'm still getting this error. I'm assuming minor releases are okay.

However I think I've narrowed it down. [This customization](https://forum.osticket.com/d/97897-multiple-ip-addresses-on-api-calls/5) seems to have broken in the latest release.

There was an issue open for it at one point but it was closed: https://github.com/osTicket/osTicket/issues/3857

The problem with that (reason why we 'modded' it in the first place) is because we run in a docker container / Kubernetes cluster which means the IP of the pod can change at any time - so the current method of restricting access to the API via IP breaks every time our cluster adjusts the workload.

This issue can be closed, but it would be nice if we didn't need to have to mod the include.php to disable the IP verification on the API which is not useful to us (I dislike custom code for this reason - because it can break during upgrades).

**Comment by joeldeteves** [comment]
Hello, sorry to re-open however it seems I have a new iteration of the same problem now.

It appears that in spite of downgrading to PHP v8.0, I am getting an error in the class.plugin.php file - this error is repeated across a fresh install so it's not my environment:

`NOTICE: PHP message: PHP Fatal error: Uncaught Error: Undefined constant "GLOB_BRACE" in /var/www/html/include/class.plugin.php:254
Stack trace:
#0 /var/www/html/include/staff/plugin-add.inc.php(15): PluginManager::allInfos()
#1 /var/www/html/scp/plugins.php(66): require('...')
#2 {main}
thrown in /var/www/html/include/class.plugin.php on line 254`

This is preventing all plugins from showing up in the list

EDIT: It seems that there is an existing issue for it here https://github.com/osTicket/osTicket/issues/6079

I will close this one again and follow that issue instead.
