### ISSUE TITLE
attachment-fs plugin interfering with the operation of the other plugins.

### ISSUE THREAD

**Issue by carloslauff** [osTicket/osTicket-plugins#235]
By enabling the attachment-fs plugin the configuration options of this plugin override the configuration options that should be presented in the other installed plugins. The other plugins stop working. By disabling the plugin the other plugins will work again.

**Comment by JediKev** [comment]
@carloslauff 

I assume you are using 1.16.x and PHP 8.0.x. If this is the case you need this:
- https://github.com/osTicket/osTicket/pull/6178/files

Cheers.

**Comment by carloslauff** [comment]
Thank you! Now it works like a charm!
