### ISSUE TITLE
oauth2 plugin broken

### ISSUE THREAD

**Issue by ChrisTG742** [osTicket/osTicket-plugins#239]
Since the last commit the oauth2 plugin no longer loads here in v1.17:

[Tue Oct 04 13:15:49.467930 2022] [php7:error] [pid 1021076] [client 172.16.0.147:57063] PHP Fatal error:  Abstract function osTicket\\Mail\\MailBoxProtocolTrait::oauth2Auth() cannot be declared private in /var/www/osTicket/upload/include/class.mail.php on line 238

Any quick fix besides re-installing the former version?

**Comment by ChrisTG742** [comment]
Seems rather be a bug in v1.17 release. In RC4 it still worked. I'll open a bug-report in the main repo instead.

**Comment by JediKev** [comment]
@ChrisTG742 

Did you download and install the latest build of the plugin? If you are using latest build, can you provide exact steps to replicate this issue?

Cheers.

**Comment by ChrisTG742** [comment]
@JediKev Thanks, it figured out that it is rather a "how to I upgrade from 1.15 and PHP7.4 to 1.17 and PHP8.0" problem. But I think I almost puzzled that out :)
