### ISSUE TITLE
OAuth2 MS plugin fails when submitting

### ISSUE THREAD

**Issue by ognalysis** [osTicket/osTicket-plugins#243]
I've recently upgraded to 1.17 from 1.10 with minimal issues.

Configuring the OAuth2 MS plugin following the guide results in an http 500 failure error upon hitting submit.

All OAuth2 configurations are entered according to the document provided [here.](https://github.com/osTicket/docs/blob/3b6b623c026c15bb267e404a4afd72b19d29f035/OAuth2/Microsoft%20Authorization%20Guide.rst)

During migration, I ran into several identical issues which were resolved by removing the related items from the database (e.g. Couldn't remove or configure LDAP plugin until I removed them from the DB and re-added them via GUI. Same with email connector.)

If there is a better place to submit this, please let me know.

**Comment by JediKev** [comment]
@ognalysis 

[Our Forum](https://forum.osticket.com) is better suited for these types of questions. But if you get 500 error that’s typically indicative of a fatal error that should be logged in one of your log files (PHP error logs, Apache/NGINX/IIS error logs, etc.).

Cheers.

**Comment by ognalysis** [comment]
Thank you. I'll head that way.
