### ISSUE TITLE
Cannot connect to 0365 Mailbox with auth-oauth2 because mailadress and upn is different

### ISSUE THREAD

**Issue by MichaelFor** [osTicket/osTicket-plugins#248]
Hello,
we use OSTicket with following Versions:
osTicket-Version | v1.17 (1d8b790)
Server-Software | Apache/2.4.38 (Debian)
MySQL-Version | 10.3.36
PHP-Version | 8.0.24
Oauth2 Client 0.6

Our Headquater is changing the domain from the mailbox, but the upn is now different.
There will not change the upn to the same and also do not will exclude the mailbox from the default policy for the mailbox mailadress.

So in this case the access to the mailbox is not work anymore.
I can successfull authenticate,
![grafik](https://user-images.githubusercontent.com/117063352/198942438-234abb0d-234d-412f-8197-e98531f6b9a7.png)
but this error is coming
![grafik](https://user-images.githubusercontent.com/117063352/198942692-27fc02b9-2939-4d90-a491-029c4c766780.png)

I wil ltake a look in the table os_config and hope to change the fields but it do not change anything
![grafik](https://user-images.githubusercontent.com/117063352/198943943-e1548679-8fd6-4990-a00a-441ea18f0817.png)

I do not understand the code complete from the auth-oauth2.phar but i see in the function
OAuth2EmailAuthBackend that there is no way to use at the moment upn different from emailadress.
Please is there a way to extend this plugin for using different upn and emailadress.

br
Michael

**Comment by JediKev** [comment]
@MichaelFor 

Please post on [the Forum](https://forum.osticket.com) next time. Github is a place to report issues, create feature requests, and submit pull requests. If you have questions or an error like this then it's better suited for the Forum.

With that being said, this has been mentioned on here and the Forum a few times. Currently we require the email you login as in MS match the email you are configuring in osTicket (we hope to improve this in the future). We state it very clearly here:
- https://docs.osticket.com/en/latest/OAuth2/Microsoft%20Authorization%20Guide.html

> Here it is **very important** to login to the email you are trying to configure in the helpdesk.


**P.S.**
You can change this functionality yourself:
- https://github.com/osTicket/osTicket-plugins/blob/1.17.x/auth-oauth2/oauth2.php#L341-L343

Cheers.
