### ISSUE TITLE
Fail to build phar on auth-ldap and storage-s3 plugins

### ISSUE THREAD

**Issue by sikksakk** [osTicket/osTicket-plugins#25]
Hey,
I tried to build the auth-ldap plugin today, but it fails with the following error;
root@helpdesk ~/core-plugins# php make.php build auth-ldap
PHP Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Entry include/Net/. cannot be created: phar error: invalid path "include/Net/." contains current directory reference' in /root/core-plugins/make.php:375
Stack trace:
#0 /root/core-plugins/make.php(375): Phar->buildFromIterator(Object(ArrayIterator))
#1 /root/core-plugins/make.php(326): PluginBuilder->_build('auth-ldap', Array)
#2 /root/core-plugins/make.php(251): PluginBuilder->run(Array, Array)
#3 /root/core-plugins/make.php(502): Module->_run('make.php')
#4 {main}

  thrown in /root/core-plugins/make.php on line 375

I noticed that also the storage-s3 plugin fails, but auth-passthru and storage-fs builds OK.

i use turnkeylinux appliance, with following php:
PHP 5.4.4-14+deb7u9 (cli) (built: Apr 18 2014 14:34:31)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies
    with XCache v2.0.0, Copyright (c) 2005-2012, by mOo
    with Xdebug v2.2.1, Copyright (c) 2002-2012, by Derick Rethans

I did a git clone, and did a "php make.php hydrate" after (which looks to run ok).

regards,

**Comment by greezybacon** [comment]
Could you see if the patch in #26 addresses this issue?

**Comment by sikksakk** [comment]
Yep, fixes the build issue! :)
