### ISSUE TITLE
Help Desk Audit Bug

### ISSUE THREAD

**Issue by Tinnitus97** [osTicket/osTicket-plugins#280]
Hello,
unfortunately the filter in the admin panel --> dashboard --> audit logs is not working anymore.
When you go to the page, entries are displayed, but as soon as you select a filter, no entries are displayed anymore.

osTicket v1.18
Apache
MySQL 10.4.28
PHP 8.2
Help Desk Audit Version 0.1 (Download Today from osticket.com website)

**Comment by JediKev** [comment]
@Tinnitus97 

Hmmm..works just fine for me. Care to share screenshots or any related errors? Can you confirm you have such data that fits the criteria from the database?

Cheers.

**Comment by Tinnitus97** [comment]
I have put 2 photos of this problem here.
The first photo shows the call of the page in admin area with correct data.
The second photo shows the state when a filter is active. 
(According to the photo above, there are definitely events in this area).

![Screenshot 2023-10-13 203509](https://github.com/osTicket/osTicket-plugins/assets/85833526/91921add-bebf-48a1-a6c0-11a550bbded4)
![Screenshot 2023-10-13 203703](https://github.com/osTicket/osTicket-plugins/assets/85833526/fd470e55-c2a0-4811-9c6b-a7565f6d98b3)

**Comment by JediKev** [comment]
@Tinnitus97 

I just tried that and it worked for me. The date range I used was `2020-10-01` -> `2023-10-13` with `Type = Department` and `Events = All`. Do you see any relevant errors in any of your logs? Can you log the queries and see what query it’s running exactly?

Cheers.

**Comment by Tinnitus97** [comment]
Hello,
my system is installed in German and when I use the plug-in version of osTicket 1.17.x everything works without problems.
When I use the plug-in version of osTicket 1.18, the error occurs.
As far as I can see, this commit is the problem:

https://github.com/osTicket/osTicket-plugins/commit/9b2f8b68f22f886d4a721597d9515076c970f492

**Comment by Tinnitus97** [comment]
Hello they have already been able to check the problem
