### ISSUE TITLE
osTicket System Update: Permissions Issue in attachments Folder

### ISSUE THREAD

**Issue by TRC1337** [osTicket/osTicket-plugins#284]
Hello Everyone,

We are planning to update our osTicket system. During the process of creating a copy, we noticed a permissions issue with all subfolders within the attachments directory.

I assume that the permissions were set the way they are for a reason. We are currently using plugin version 0.3p1 "Attachments on the filesystem."

Could you please provide guidance on how the update is intended to be performed without adjusting the permissions? Since this is a hosting server and we do not have root access, we need to ensure that the update process does not require changing permissions.

Thank you for your assistance.

Best regards,

**Comment by JediKev** [comment]
@TRC1337 

1. This is the wrong repo. This is the Plugins repo; not core repo.
2. We do not use GitHub for support at all. You will need to [post on the Forum instead](https://forum.osticket.com).
3. We have an [Upgrade Guide](https://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html) here.

Cheers.
