### ISSUE TITLE
Microsoft oAuth mail stopped working because of deprecated endpoint

### ISSUE THREAD

**Issue by jjvanrossum** [osTicket/osTicket-plugins#291]
As described here in de best answer; the API V2 endpoint is not available anymore, but inserting the endpoint for graphql doesn't resolve the issue.

https://forum.osticket.com/d/105728-ms-oauth2-error-the-api-version-v2-has-been-depreciated

**Comment by JediKev** [comment]
@jjvanrossum 

Please read the whole thread for a resolution before posting. You would’ve seen this:
- https://forum.osticket.com/d/105728-ms-oauth2-error-the-api-version-v2-has-been-depreciated/41

With that being said we will have an official updated plugin soon.

Cheers.
