### ISSUE TITLE
LDAP Auth | Searching for user with umlauts fails

### ISSUE THREAD

**Issue by NickCloudAT** [osTicket/osTicket-plugins#293]
Installed OsTicket:
![image](https://github.com/user-attachments/assets/cd064c4f-df0c-44cf-88cc-db96b77feb59)

Problem is;
When I want to change the owner of a Ticket to a user that has not yet been registered in the "Users" tab, they do appear there but the autofill wont happen if the user has an umlaut in his name..

I'm talking about this window:
![image](https://github.com/user-attachments/assets/67af71c1-f19d-428d-b7bd-82f3a882bbc0)

Searching for a user with umlauts works fine, but as soon as I click on a user with umlauts nothing happens and I get this error in the browser console:
https://server/scp/ajax.php/users/select/auth%3Aldap.p1i2%3ACN%3Duserfirsthal>%C3%84RF%20Gregor%2COU%3DNOS%2COU%3DBenutzer%2COU%3Dsensitive%2CDC%3Dsensitive%2CDC%3Dsensitive with 404 not found.

**Comment by JediKev** [comment]
@NickCloudAT 

Thank you for the report. This has been addressed with the following pull request in core osTicket:
- https://github.com/osTicket/osTicket/pull/6768

Keep in mind that the referenced pull request is subject to change as it has not been fully approved/merged. Nonetheless, it will be included in the next set of releases once approved and merged.

Cheers.
