### ISSUE TITLE
HTTP Passthru working but not for Staff Backend

### ISSUE THREAD

**Issue by madd15** [osTicket/osTicket-plugins#33]
Hi I updated my HTTP Passthru from here to get the client http passthru but now its not working for the staff login for scp. Staff have to login would be nice to have passthru on both sides

**Comment by ntozier** [comment]
Version of osTicket?
Version of plugin?

**Comment by madd15** [comment]
osTicket- V1.9.1
Plugin- from here - authored on May 20

**Comment by Chefkeks** [comment]
Jared (greezybacon) updated the http-passthru auth plugin to v0.2, should be the same version as "authored May 20", but anyway I suggest downloading and using it: www.osticket.com/download
Additionally did you make sure staff and client auth option are enabled in the plugin config page? 
Do you use apache or IIS?
In case of apache, see here a little how-to for apache + AD SSO with the auth pass thru plugin:
http://osticket.com/forum/discussion/comment/82591/#Comment_82591

**Comment by madd15** [comment]
When I changed to the version from www.osticket.com/download not even the client side worked. I am also using IIS.

**Comment by madd15** [comment]
After completely starting from scratch with both LDAP and HTTP Passthru plugins i have got them to work.

**Comment by MelkiSaputro** [comment]
Dear Madd15,

Could you help me, Cause i had installed HTTP Passthru plugin but i dont see which configuration set to set and IP or API HTTP Passthru on the plugin.

Authentication Modes
Authentication modes for clients and staff members can be enabled independently. Client discovery can be supported via a separate backend (such as LDAP)
Staff Authentication:  
 Enable authentication of staff members (click)
Client Authentication:  
 Enable authentication and discovery of clients (click)

Only this two set config can be seen. Is there any .php that i need to change ?

Thanks in advance.
