### ISSUE TITLE
form fields too short

### ISSUE THREAD

**Issue by rhavenn** [osTicket/osTicket-plugins#34]
Seems the new release, 1.9.1, changed the default form field length.

I'm using the latest phar's from osticket.com (last week) and making changes like adding DNS servers to the LDAP plugin or adding a path to the storage-fs plugin gets a maxlength of 30 which is, IMHO, way to short. The old one was, I think, 120.

**Comment by greezybacon** [comment]
I agree the default should be much longer. This would be a bug for osTicket, though.

**Comment by greezybacon** [comment]
@rhavenn could you maybe try the patch in #63?
