### ISSUE TITLE
auth-oauth login attempt with google+ sends to blank screen

### ISSUE THREAD

**Issue by aarobc** [osTicket/osTicket-plugins#41]
I've enabled login for agents and clients, entered in the clientID and secret generated in google apps. 

When I try to login by clicking the "Sign in with Google" icon I am directed to a white page.
In the URL it just shows: <domain>/login.php?do=ext&bk=google.client.

Any pointers on tracking down what's wrong here?
OSticket v1.9.2 
Server Software:    Apache/2.2.15 (CentOS)
PHP Version:    5.3.3
MySQL Version:  5.1.73

**Comment by ntozier** [comment]
Have you disabled SELinux and tried again?
Are you seeing any errors in your PHP error log?

**Comment by aarobc** [comment]
SELinux is indeed disabled. I checked the error log and am getting the following error message:

PHP Fatal error:  Class 'ohmy\Auth2' not found in /var/www/support/include/plugins/auth-oauth/google.php on line 15

I guess I need to find that somewhere? Shouldn't it be included in the repo?

**Comment by aarobc** [comment]
Okay, after some research this is what I found:
After cloning the repo, you have to run:

php make.php hydrate

That will pull down the dependencies. Next, you have to move the auth-oath directory and the lib directory up so they're directly in include/plugins/.

Create OAth credentials in google developer settings and enter them into the plugin. 
For the Authorized Redirect URI enter in yourdomainhere/api/auth/ext

Under the Developer console select "Consent Screen" and enter appropriate information. 

When I try to log in, I get tho the consent screen, but when I accept, I'm redirected to:
mydomain/api/auth/ext?state=53c4.... 

And a message saying "The requested URL /api/auth/ext was not found on this server."

I feel I'm close, but what am I missing?

**Comment by greezybacon** [comment]
There is a .htaccess file in the api/ folder, and the web.config file is configured to hand off the request back through the request dispatcher. Do you have something turned off in your web server?

**Comment by aarobc** [comment]
That was it. I enabled .htaccess files on the server and it seems to be working perfectly. Much thanks.

**Comment by selvinbailey** [comment]
Hello aarobc, I am using godaddy hosting and I don't know exactly how this is done.

**Comment by selvinbailey** [comment]
I have the following in my .htaccess file.

<IfModule mod_rewrite.c>

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} (.*/api)

RewriteRule ^(.*)$ %1/http.php/$1 [L]

</IfModule>

**Comment by aarobc** [comment]
selvinbailey, the configuration would have to be done in apache. If you're using a shared hosting account you'll need to contact them and have them enable .htaccess files.

**Comment by JNoel1234** [comment]
I fell like I'm so close to getting mine to work. When I go to login with Google I get to the authorization page and click "Allow" but then after that all I get is a blank page. The URL looks like this:

http://example.zapto.org/osticket/api/auth/ext?state=4de718e42d79a74e9bacf1676bebc279&code=4/GwSirF_ITmN6XGS7hnNeWcB3jxvehcrmfUuBYwcpERI#

What am I missing?

**Comment by marbuziba** [comment]
Hello,
I have the same problem as you, I get the error of ohmy \ Auth2. But I can not run the php make.php hydrate command since I already have the application uploaded to an external server.

I want to do it manually, from this page https://www.webpreprod.com/issue/utiliser-protocole-oauth-20-osticket-se-connecter-compte-google-facebook
I have seen that it can be done but I do not know where I have to locate the "src" folder inside the folder structure.

Can you help me?

**Comment by hossam-abdelmajeed** [comment]
I had the same problem, so I enabled **SELinux** and nothing happens, So I kept reading comments, and found that  @aarobc  had a solution just after @greezybacon  mentioned  

>  .htaccess file in the api/ folder

So, I found the link below, showing how to enable  .htaccess file in Linux, and yaaaaay it's now working perfectly..
Thanks all, Best luck.

[https://support.severalnines.com/hc/en-us/articles/212426163-Enable-AllowOverride-for-Apache](https://support.severalnines.com/hc/en-us/articles/212426163-Enable-AllowOverride-for-Apache)
