### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by Esya** [osTicket/osTicket-plugins#43]
Hi guys.

After trying to sign in using oauth I get a 404 for `/api/auth/ext`, any idea why the routing is not done correctly ?

**Comment by Esya** [comment]
Fixed it by modifying the apache config, this is probably the only part of the website that needs htaccess and did not notice it. This would need more documentation.

**Comment by ntozier** [comment]
Can you please post your .htaccess changes here in case someone else needs to do this?

**Comment by Esya** [comment]
I used the one in  `api/.htaccess` but the problem was my apache config, I didnt notice osticket needed these so I just added this to my apache vhost config

```
Options Indexes FollowSymLinks MultiViews
AllowOverride All
Order allow,deny
allow from all
```

And it works fine now.
