### ISSUE TITLE
Tickets removed from the DB

### ISSUE THREAD

**Issue by adilshahzad** [osTicket/osTicket-plugins#46]
Hi,
We're using this system since 2012 and we upgraded to ver:1.8.1 early 2014. Our client complaint that they've raised the tickets and they also received the acknowledgment email from the system along with the ticket number but the strange thing is that these ticket does not exists in the DB.
I've checked the table in the DB and didn't see the ticket numbers that our clients complaint about. The missing tickets are on 4 and 5 of Aug-2014. Can you please help to resolve the issue?

Thanks,
Adil

**Comment by greezybacon** [comment]
This doesn't seem to concern plugins for osTicket. Secondly, if the tickets were deleted after they were created, you would no find them in the database.
