### ISSUE TITLE
oauth: Google + not working

### ISSUE THREAD

**Issue by bhanu2217** [osTicket/osTicket-plugins#58]
The plugin doesn't seem to be working. I have entered Google + client id & secret
It takes me to this page and shows white blank page login.php?do=ext&bk=google.client
Os Ticket Version: Version 1.9.4

**Comment by bhanu2217** [comment]
Can anyone please specify how to generate the phar file for this plugin?
I read about Hydrate command but i am guessing i am running it wrong. The plugin has four files the make.php file should it be in same folder as plugin files or outside plugin files folder?

Also when i run php make.php hydrate it just generates composer.phar & composer.json
Composer.phar is empty
and composer.json has following code

{
    "name": "osTicket/core-plugins",
    "repositories": [
        {
            "type": "pear",
            "url": "http://pear.php.net"
        }
    ],
    "require": [],
    "config": {
        "vendor-dir": "lib"
    }
}

Where am i going wrong?

**Comment by bhanu2217** [comment]
Figured out how to generate phar file but following command
php make.php build auth-oauth

but i am still getting following error

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/Applications/AMPPS/www/lib/ohmy/auth/src/): failed to open dir: No such file or directory' in /Applications/AMPPS/www/make.php:361
Stack trace:
#0 /Applications/AMPPS/www/make.php(361): RecursiveDirectoryIterator->__construct('/Applications/A...')
#1 /Applications/AMPPS/www/make.php(319): PluginBuilder->_build('auth-oauth', Array)
#2 /Applications/AMPPS/www/make.php(240): PluginBuilder->run(Array, Array)
#3 /Applications/AMPPS/www/make.php(523): Module->_run('make.php')
#4 {main}
  thrown in /Applications/AMPPS/www/make.php on line 361

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/Applications/AMPPS/www/lib/ohmy/auth/src/): failed to open dir: No such file or directory' in /Applications/AMPPS/www/make.php:361
Stack trace:
#0 /Applications/AMPPS/www/make.php(361): RecursiveDirectoryIterator->__construct('/Applications/A...')
#1 /Applications/AMPPS/www/make.php(319): PluginBuilder->_build('auth-oauth', Array)
#2 /Applications/AMPPS/www/make.php(240): PluginBuilder->run(Array, Array)
#3 /Applications/AMPPS/www/make.php(523): Module->_run('make.php')
#4 {main}
  thrown in /Applications/AMPPS/www/make.php on line 361

**Comment by ntozier** [comment]
It's recommended that you download the pre-hydrated plugins from the web page.
http://osticket.com/download
Click on the Plugin tab.

**Comment by bhanu2217** [comment]
Pre hydrated for Google + is not available.

**Comment by Chefkeks** [comment]
http://osticket.com/download-edge ;)

**Comment by bhanu2217** [comment]
Thank You :-)

**Comment by bhanu2217** [comment]
I am now facing exact same issue as listed here http://osticket.com/forum/discussion/77385/howto-configure-the-oauth2-plugin

**Comment by bhanu2217** [comment]
Solved the issue using this http://www.webpreprod.com/issue/utiliser-protocole-oauth-20-osticket-se-connecter-compte-google-facebook

**Comment by anandselvarasu** [comment]
@bhanu2217 - How solved ? Can you pls help me..

**Comment by saurabhumalkar** [comment]
Nothing helps with this. Can someone please provide detailed solution. Thank you.

**Comment by ntozier** [comment]
Did you follow the guide that the @bhanu2217 linked above saying that it solved his issue?

**Comment by saurabhumalkar** [comment]
@ntozier I did follow the guide mentioned by @bhanu2217 but it doesn't help.  It seems I am facing same problem as @bhanu2217 was facing before he solved it. I am using v1.10

**Comment by Mukesh753** [comment]
The plugin doesn't seem to be working. I have entered Google + client id & secret
It takes me to this page and shows white blank page login.php?do=ext&bk=google.client
Os Ticket Version: Version 1.14.4

**Comment by ntozier** [comment]
@Mukesh753 
This bug report was closed in 2015.  Responding to closed bug reports isn't likely to garner responses.

This plugin was written for v 1.8.x and was never released (or it would be on the https://osticket.com/download page).  It does not look like it was ever upgraded to work with 1.9, 1.10, 1.11, 1.12, 1.14, or 1.15 (current).
