### ISSUE TITLE
Custom Authentication Plugin

### ISSUE THREAD

**Issue by bhanu2217** [osTicket/osTicket-plugins#59]
I have created a custom authentication plugin and uploaded the phar file under plugin folder and clicked on add new plugin in admin panel i don't see anything in plugin list?

Am i doing anything wrong?
I followed the steps same way as was done for Google Auth plugin
Is there some documentation on how to create plugins for OS Ticket.

**Comment by ntozier** [comment]
We cannot really support your custom plugin, and especially cannot even give you hints with out seeing the code.

There is no official plugin documentation.  There is an unofficial documentation that can easily find via google.  http://osticket.com/forum/discussion/77864/unofficial-plugin-development-guide

**Comment by bhanu2217** [comment]
Thank You.
