### ISSUE TITLE
[LDAP/AD] User/Staff dropdown-list

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket-plugins#6]
Hi osTicket-Team,
first I need to say your doing a really great job ;)

We have tested the yesterday released osTicket-1.8.1-dpr with the ldap-auth-plugin. Based on that test are here some suggestions/enhancements about the AD authentication plugin which would make it even more comfortable ;)

Here our thoughts:
May you could provide an option to enable a dropdown-list filled with all the AD users. That dropdown-list could be used in addition to (OR instead of) the user search and (to speed up things a little bit ;) ) be pre-filled with an array of the user information (name, mail, phone, etc.). Additionally there should be an option to update that cached dropdown-list every n minutes/hours (update frequency) to make sure new users get added and old users get removed.

Based on our long lasting experience with our self-made ticket system this is especially useful/user-friendly for the not yet implemented client side. When a user creates a ticket the user really likes to easily select his/her name from a dropdown-list instead of typing it and let the system search for it - even though the fields are then auto-filled for it!

Attached is also a screenshot of an older and modded test installation of osTicket with the dropdown-list. (If you're missing the normal input fields you need to know that we decided to hide them completely since it annoyed us to have both, dropdown-list and normal input fields)

We hope you like that idea and may implement it into the ad plugin.
Since you're able to read german (greezybacon) I end up with some german words :D

Schöne Grüße und vielen Dank,
Chefkeks

![osticket-dropdown-list](https://f.cloud.github.com/assets/2871833/1983195/407de10a-8410-11e3-885e-998ef2b22e1c.png)

**Comment by GeekSage** [comment]
I definitely don't like the dropdown idea showing all AD users.  What if you work in a company where there's over 20k AD users (which is the case in my situation)?  Something like that would only work well if you had a small number of AD users in the system.

**Comment by Chefkeks** [comment]
Sure, in that case with 20k users it's not useful, but here we only have a few hundred users ( < 300). Based on our experience we found this the best way to a) gather information from the sender and b) keep it easily/user-friendly for the client as well. But therefore I suggested to make that as an optional possibility to enable that dropdown-list, not a required one ;)

**Comment by ntozier** [comment]
I'm going to echo @GeekSage that a large number of users will make your suggestion... unwieldy.  Additionally once client accounts are implemented more fully, clients will not need to search through a drop down box as they would log into the ticket system like they would any other service.  Lastly I would like to add that giving away the username to all your users is like giving away half the kingdom security wise... especially right now since the password is a string of six numbers.

**Comment by greezybacon** [comment]
I don't like this idea either, but it might could be implemented with a typeahead box that queries the directory in real time

**Comment by Chefkeks** [comment]
For some reasons we did not think of a typeahead box (we don't know why, but we agree with that typeahead box here :D), but that would definitely be an option instead of a dropdown-list (which is really a no-go with 20k users) !

**Comment by GeekSage** [comment]
Yea, a customizable type ahead would be nice (customizable in the way that it won't start till x number of characters have been entered).  That would help reduce the load for larger lists.

**Comment by ntozier** [comment]
I would actually recommend that a configuration setting be put in to the ost-config [file or table] that dictates how many letters need to be entered before it runs the query.  So that individual admins can specify an override value if they feel that say 3 or 4 [default] is not sufficiently optimal for their implementation.  This would allow people like @GeekSage to put in say 5 and @Chefkeks to put in say 2.

**Comment by Chefkeks** [comment]
Since LDAP client login and also SSO are working, I will close this issue myself since it's no longer of interest.

**Comment by phillf** [comment]
What if you used a similar approach to the User select field? Not displaying every single user at the same time but allowing for a search to happen. 

I, like others, don't agree with the approach that was suggested. ServiceNow does something similar except you click an icon which opens a user picker in a popup window and it starts by displaying EVERY SINGLE USER. It's at least paginated but still when you are in an enterprise which encompasses at least 5 hospitals (not counting any Urgent Care or Community practices) it becomes overwhelming to the average user if they are unfamiliar with the interface.
