### ISSUE TITLE
auth-ldap

### ISSUE THREAD

**Issue by blozzy** [osTicket/osTicket-plugins#64]
hi, i've installed the newest osticket and 0.6er ldap auth from here and receiving this failure on iis now, ldap extension in iis is enabled:

Fatal error: Function name must be a string in C:\inetpub\wwwroot\helpdesk\include\plugins\auth-ldap\config.php on line 36 

DOMAIN (textbox) has been filled

**Comment by greezybacon** [comment]
What version of PHP are you using?

**Comment by greezybacon** [comment]
Sorry about the issue. It's fixed and published to osticket.com/download

**Comment by blozzy** [comment]
5.34
Am 09.04.2015 19:30 schrieb "Jared Hancock" notifications@github.com:

**Comment by greezybacon** [comment]
5.34?

**Comment by Chefkeks** [comment]
@greezybacon
It's the PHP version you asked for ;)

**Comment by blozzy** [comment]
yes 5.34

2015-04-09 22:08 GMT+02:00 Jared Hancock notifications@github.com:

> 5.34?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osTicket/core-plugins/issues/64#issuecomment-91343422
> .

## 

Andreas Strauß
Hartweg 12
DE-71334 Waiblingen
Tel.: +49 7151 9449351
Cell: +49 17645767061

**Comment by ntozier** [comment]
There has never been a PHP 5.34 release... ever.  There was a 5.3.4 for a month back in 2010 though.
http://php.net/releases/

**Comment by blozzy** [comment]
sorry 5.4.34

2015-04-09 22:29 GMT+02:00 ntozier notifications@github.com:

> There has never been a PHP 5.34 release... ever. There was a 5.3.4 for a
> month back in 2010 though.
> http://php.net/releases/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osTicket/core-plugins/issues/64#issuecomment-91348040
> .

## 

Andreas Strauß
Hartweg 12
DE-71334 Waiblingen
Tel.: +49 7151 9449351
Cell: +49 17645767061

**Comment by blozzy** [comment]
now i am getting this:

Warning: require_once(include/Net/LDAP2.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\helpdesk\include\plugins\auth-ldap\config.php on line 132 Fatal error: require_once(): Failed opening required 'include/Net/LDAP2.php' (include_path='./;C:/inetpub/wwwroot/helpdesk/include/;C:/inetpub/wwwroot/helpdesk/include/pear/;C:\inetpub\wwwroot\helpdesk\include\plugins\auth-ldap/include') in C:\inetpub\wwwroot\helpdesk\include\plugins\auth-ldap\config.php on line 132

**Comment by Chefkeks** [comment]
Did you download the latest version (currently 0.6.2) from osticket.com/download (recommended) or here from github?

**Comment by blozzy** [comment]
yes tried this version, save issue has been fixed now. should the ldap2.php been installed seprately with the pear module ?

**Comment by ntozier** [comment]
If you downloaded it from osticket.com/download (recommended) then its included.
If you downloaded it from github you get that error unless you follow the hydrate instructions.

**Comment by Hannibal226** [comment]
I had also some problems with installing the new version of LDAP plugin.
The problem is, u can't handle it really, once it's there...
There's one step which seems to work finally and is quite easy (if doing first).

So I created a local user login who is admin.
Then I "deleted" the plugin, which first deactivate it, so u have to do twice.
After that load the new one.

Maybe in was just random luck here, but for me it worked after a lot of problems.
So first "clear deleting" of the ldap plugin and afterwards install the new one.

Good luck.
CHEERS

**Comment by greezybacon** [comment]
@Hannibal226 I've noticed that working with broken or missing plugins is very difficult for osTIcket. I've (attempted to) address this in the `develop-next` branch by automatically disabling plugins that cannot be found or cannot be loaded

**Comment by Hannibal226** [comment]
@greezybacon 
+1
That should beware of a lot problems...
