### ISSUE TITLE
Cannot increase attachment size > 2Mb

### ISSUE THREAD

**Issue by GreenMamba** [osTicket/osTicket-plugins#65]
These days screenshots from Windows and videos of problems are quite large. That's OK as long as they are of the allowed format.

However OSTicket only has options for 512kb, 1mb and 2mb.... which is nothing these days. Its the same issue for Agent attachments or EndUser attachments.

How about allowing much bigger sizes? Or even better put an text entry box instead of a limited dropdown box so we can choose the maximum sizes ourselves?

**Comment by GreenMamba** [comment]
Gmail accepts messages + attachments up to 25Mb these days.

**Comment by protich** [comment]
This is not an issue with osTicket per se -- the limit is dependent on your php.ini setting.  What is the point of allowing more than your php setting?

**Comment by ntozier** [comment]
What Peter is saying is that osTicket  bases available file size limitations based on the PHP configuration.  This is not a problem with osTicket.  It means that you need to change the setting on your webserver.
1. Configure PHP to accept larger files by altering the upload_max_filesize directive.

For more information on this directive see:
http://php.net/upload-max-filesize
1. Restart the Webserver software. (Varies by Webserver)
2. Alter your osTicket Attachment settings at Admin panel -> Settings -> Tickets.  Note that you can also specify a different size for agents and users.

**Comment by GreenMamba** [comment]
my bad... thanks for the info!

**Comment by timwhite** [comment]
Can we get the information box updated to include this information? It would be nice for a new user, not to have to Google, find this issue, then fix it, when we could present this information in the interface.
