### ISSUE TITLE
language in profile.php i18n

### ISSUE THREAD

**Issue by DieQuelle** [osTicket/osTicket-plugins#82]
Buttons incorrectly translated.

http://imgur.com/KNwSbqm

**Comment by ntozier** [comment]
There is no profile.php in this repository.

Language translations are done here:
https://crowdin.com/project/osticket-official

**Comment by DieQuelle** [comment]
im sorry, can you move this to 1.8 instead /plugins.

**Comment by ntozier** [comment]
Please close this and open one in the appropriate repo.
I dont think that they can be moved between repos.
(If they can... I certainly do not have access to do it.)

**Comment by DieQuelle** [comment]
--> https://github.com/osTicket/osTicket-1.8/issues/2546
